import './globals.css';
import type { Metadata } from 'next';
import { Inter } from '@/lib/fonts';
import SmoothScrollProvider from '@/components/SmoothScrollProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'THE VAULT by Karan Desai',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <head>
        <meta
          name='google-site-verification'
          content='Q2JdPP5T_TVL9xIA98ozuSkGZd2J7ao-WOEwK4HpvHM'
        />
      </head>
      <body className={inter.className}>
        {/* {children} */}
        <SmoothScrollProvider>{children}</SmoothScrollProvider>
      </body>
    </html>
  );
}
